/**
 * Remote project paths.
 *
 * A project that lives on an SSH host is identified by a URI,
 * `ssh-remote://<profileId><absolute POSIX path>`, never by a bare POSIX path.
 * The reason is in design/remote-ssh.md section 3.2: on Windows
 * `path.resolve('/home/x')` becomes `E:\home\x`, and on Linux or macOS the same
 * path may exist locally, so a bare remote path handed to any code path that
 * has not been taught about remote projects would act on a local folder. The
 * URI is not absolute on any platform and does not exist on disk, so such code
 * fails closed.
 *
 * Everything here is pure JS and POSIX-only on purpose: the renderer's `path`
 * is main's `path` module over IPC, which is `path.win32` on Windows and would
 * turn `/home/x/src` into `\home\x\src`. Remote paths are manipulated through
 * this module and nothing else, in both processes.
 *
 * Two refusals are built in rather than left to callers:
 *   - a `..` that would climb above `/` throws instead of being clamped, so a
 *     crafted relative path cannot silently become a different absolute one;
 *   - control characters (C0, DEL, C1) throw, because every remote command is
 *     built on one line and a newline in a path would end it.
 */

'use strict';

const SCHEME = 'ssh-remote://';

/** Profile ids are generated by main: 8 characters of [a-z0-9]. */
const PROFILE_ID_RE = /^[a-z0-9]{8}$/;

function remotePathError(message, code = 'REMOTE_PATH_INVALID') {
  const error = new Error(message);
  error.code = code;
  return error;
}

/** True when `value` contains a C0 control, DEL or a C1 control character. */
function hasControlChars(value) {
  const text = String(value);
  for (let i = 0; i < text.length; i++) {
    const code = text.charCodeAt(i);
    if (code < 0x20 || (code >= 0x7f && code <= 0x9f)) return true;
  }
  return false;
}

function assertClean(value) {
  if (typeof value !== 'string') throw remotePathError('Remote path must be a string');
  if (hasControlChars(value)) throw remotePathError('Remote path contains a control character');
}

/** True when `value` is an `ssh-remote://` URI. Windows paths, POSIX paths and relative paths are not. */
function isRemotePath(value) {
  return typeof value === 'string' && value.startsWith(SCHEME);
}

function isValidProfileId(id) {
  return typeof id === 'string' && PROFILE_ID_RE.test(id);
}

/**
 * Normalise a POSIX path: collapse duplicate slashes, resolve `.` and `..`.
 * An absolute path whose `..` climbs above `/` throws. A relative path keeps
 * its leading `..` segments, since there is no root for it to escape.
 */
function normalizePosix(value) {
  assertClean(value);
  if (value === '') return '.';
  const absolute = value.startsWith('/');
  const out = [];
  for (const segment of value.split('/')) {
    if (segment === '' || segment === '.') continue;
    if (segment === '..') {
      if (out.length && out[out.length - 1] !== '..') { out.pop(); continue; }
      if (absolute) throw remotePathError('Remote path escapes the root', 'REMOTE_PATH_ESCAPE');
      out.push('..');
      continue;
    }
    out.push(segment);
  }
  if (absolute) return '/' + out.join('/');
  return out.length ? out.join('/') : '.';
}

/**
 * Split a URI into its profile id and its normalised absolute POSIX path.
 * @param {string} uri
 * @returns {{ profileId: string, path: string }}
 */
function parse(uri) {
  if (!isRemotePath(uri)) throw remotePathError('Not an ssh-remote:// URI');
  assertClean(uri);
  const rest = uri.slice(SCHEME.length);
  const slash = rest.indexOf('/');
  const profileId = slash === -1 ? rest : rest.slice(0, slash);
  if (!isValidProfileId(profileId)) throw remotePathError('Invalid host profile id in remote URI');
  const rawPath = slash === -1 ? '/' : rest.slice(slash);
  return { profileId, path: normalizePosix(rawPath) };
}

/** `parse` that returns null instead of throwing. */
function tryParse(uri) {
  try { return parse(uri); } catch { return null; }
}

/**
 * Build a URI from a profile id and an absolute POSIX path.
 * @param {string} profileId
 * @param {string} posixPath
 */
function format(profileId, posixPath) {
  if (!isValidProfileId(profileId)) throw remotePathError('Invalid host profile id');
  assertClean(posixPath);
  if (!posixPath.startsWith('/')) throw remotePathError('Remote path must be absolute');
  return SCHEME + profileId + normalizePosix(posixPath);
}

/** The absolute POSIX path of a URI, or the normalised value when it is already a POSIX path. */
function toPosix(value) {
  return isRemotePath(value) ? parse(value).path : normalizePosix(value);
}

/** Apply `fn` to the POSIX part of `value`, re-wrapping a URI around the result. */
function mapPath(value, fn) {
  if (isRemotePath(value)) {
    const { profileId, path } = parse(value);
    return format(profileId, fn(path));
  }
  return fn(value);
}

/**
 * POSIX join. Keeps the URI wrapper when the first argument is a URI.
 * Every segment is checked for control characters; the result is normalised,
 * so a `..` climbing above `/` throws.
 */
function join(base, ...segments) {
  for (const s of segments) assertClean(s);
  return mapPath(base, (p) => normalizePosix([p, ...segments].filter((s) => s !== '').join('/')));
}

function dirnamePosix(p) {
  const n = normalizePosix(p);
  if (n === '/') return '/';
  const i = n.lastIndexOf('/');
  if (i === -1) return '.';
  if (i === 0) return '/';
  return n.slice(0, i);
}

function dirname(value) {
  return mapPath(value, dirnamePosix);
}

function basename(value, ext) {
  const p = toPosix(value);
  if (p === '/') return '';
  const name = p.slice(p.lastIndexOf('/') + 1);
  if (ext && name.endsWith(ext) && name !== ext) return name.slice(0, -ext.length);
  return name;
}

function extname(value) {
  const name = basename(value);
  const dot = name.lastIndexOf('.');
  if (dot <= 0) return '';
  return name.slice(dot);
}

function normalize(value) {
  return mapPath(value, normalizePosix);
}

/**
 * Relative POSIX path from `from` to `to`. Both must be URIs on the same
 * profile, or both absolute POSIX paths.
 */
function relative(from, to) {
  let a, b;
  if (isRemotePath(from) || isRemotePath(to)) {
    const pa = parse(from), pb = parse(to);
    if (pa.profileId !== pb.profileId) throw remotePathError('Paths are on different hosts');
    a = pa.path; b = pb.path;
  } else {
    a = normalizePosix(from); b = normalizePosix(to);
    if (!a.startsWith('/') || !b.startsWith('/')) throw remotePathError('relative() needs absolute paths');
  }
  const as = a === '/' ? [] : a.slice(1).split('/');
  const bs = b === '/' ? [] : b.slice(1).split('/');
  let i = 0;
  while (i < as.length && i < bs.length && as[i] === bs[i]) i++;
  return [...as.slice(i).map(() => '..'), ...bs.slice(i)].join('/');
}

/**
 * True when `child` is `parent` or lies below it. URIs must share a profile.
 * Case-sensitive: POSIX file systems are.
 */
function isInside(child, parent) {
  let c, p;
  if (isRemotePath(child) || isRemotePath(parent)) {
    const pc = tryParse(child), pp = tryParse(parent);
    if (!pc || !pp || pc.profileId !== pp.profileId) return false;
    c = pc.path; p = pp.path;
  } else {
    try { c = normalizePosix(child); p = normalizePosix(parent); } catch { return false; }
    if (!c.startsWith('/') || !p.startsWith('/')) return false;
  }
  if (p === '/') return true;
  return c === p || c.startsWith(p + '/');
}

module.exports = {
  SCHEME,
  PROFILE_ID_RE,
  isRemotePath,
  isValidProfileId,
  hasControlChars,
  parse,
  tryParse,
  format,
  toPosix,
  join,
  dirname,
  basename,
  extname,
  normalize,
  relative,
  isInside,
};
